
apiVersion: v1
kind: Service
metadata:
  name: note-service
spec:
  selector:
    app: note
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note
  template:
    metadata:
      labels:
        app: note
    spec:
      containers:
        - name: note-container
          image: saruuj94/note-js:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongodb-service:27017/dev
          imagePullPolicy: Always
